# Default values for kong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kong:
  image: kong:latest
  suspend: false
  gvc: dev
  create_gvc: false # If deployed in existing GVC, set to false
  name: kong-postgres # Choose a unique name so you don't override other clusters on your system
  # locations:  # Relevant only if create_gvc=true
  #   - aws-us-east-2   replicas: 2
  replicas: 2
  cpu: 2 # For millicores us 'm' like 500m
  memory: 4000Mi # Gi / Mi
  # To disable all traffic, comment out the corresponding rule. Docs: https://docs.controlplane.com/concepts/security#firewall
  firewall:
    internal_inboundAllowType: "same-org" # Options: same-org / same-gvc
    external_inboundAllowCIDR: 0.0.0.0/0 # Provide a comma-separated list
    external_outboundAllowCIDR: "0.0.0.0/0" # Provide a comma-separated list
  configurations:
    kong:
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_LOG_LEVEL: "notice" # https://nginx.org/en/docs/ngx_core_module.html#error_log
    ### IMPORTANT: Only 'postgres' or 'dbless' can be used; 
    postgres: # This is supported in single-location GVCs, for multi region DB use pgEdge
      # KONG_PG_HOST: pgcat.pgcat-pgedge.cpln.local # Provide Postgres host address if existing
      POSTGRES_PORT: 7654
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: ofk430f259409438jd923r1803j4
      POSTGRES_USER: kong
      image: postgres:16.2
      cpu: 1 # When KONG_PG_HOST is not provided.  For millicores us 'm' like 500m
      memory: 1500Mi # Gi / Mi When KONG_PG_HOST is not provided
    ### IMPORTANT: Only 'postgres' or 'dbless' can be used; 
    dbless: false
    #   KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    


