{{- if .Values.kafka_client }}
kind: workload
name: kafka-client
gvc: {{ .Values.kafka.gvc }}
tags: {}
spec:
  type: standard
  containers:
    - name: kafka
      args:
        - '-c'
        - sleep infinity
      command: /bin/bash
      cpu: {{ .Values.kafka_client.cpu }}
      image: {{ .Values.kafka_client.image }}
      inheritEnv: false
      memory: {{ .Values.kafka_client.memory }}
      ports:
        - number: 9092
          protocol: tcp
  defaultOptions:
    autoscaling:
      maxConcurrency: 0
      maxScale: 3
      metric: cpu
      minScale: 1
      scaleToZeroDelay: 300
      target: 100
    capacityAI: false
    debug: false
    suspend: false
    timeoutSeconds: 5
  firewallConfig:
    external:
      inboundAllowCIDR: []
      outboundAllowCIDR:
        - 0.0.0.0/0
      outboundAllowHostname: []
      outboundAllowPort: []
    internal:
      inboundAllowType: same-gvc
      inboundAllowWorkload: []
  localOptions: []
  supportDynamicTags: false
{{- end }}